import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Disclaimer',
  description: 'KDP Niche Finder is an independent third-party tool. Not affiliated with Amazon.com, Inc. or any third-party brands referenced. AI-generated content is for informational purposes only.',
  alternates: { canonical: '/disclaimer' },
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} style={{ marginBottom: '3rem' }}>
      <h2 style={{
        fontFamily: 'var(--font-display)',
        fontSize: '1.25rem',
        fontWeight: 700,
        color: 'var(--color-ink)',
        marginBottom: '1rem',
        paddingBottom: '0.5rem',
        borderBottom: '1px solid var(--color-border)',
      }}>
        {title}
      </h2>
      {children}
    </section>
  )
}

function H3({ children }: { children: React.ReactNode }) {
  return (
    <h3 style={{
      fontFamily: 'var(--font-display)',
      fontSize: '1rem',
      fontWeight: 600,
      color: 'var(--color-ink)',
      marginTop: '1.5rem',
      marginBottom: '0.5rem',
    }}>
      {children}
    </h3>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: '0.9375rem', color: 'var(--color-ink-2)', lineHeight: 1.7, marginBottom: '0.75rem' }}>{children}</p>
}

function Ul({ items }: { items: React.ReactNode[] }) {
  return (
    <ul style={{ paddingLeft: '1.5rem', marginBottom: '0.75rem', display: 'flex', flexDirection: 'column', gap: '0.375rem' }}>
      {items.map((item, i) => (
        <li key={i} style={{ fontSize: '0.9375rem', color: 'var(--color-ink-2)', lineHeight: 1.6 }}>{item}</li>
      ))}
    </ul>
  )
}

export default function DisclaimerPage() {
  return (
    <div style={{ background: 'var(--color-canvas)', minHeight: '100vh' }}>
      {/* Hero */}
      <section style={{ background: 'var(--color-surface)', borderBottom: '1px solid var(--color-border)', padding: '64px 48px 48px' }}>
        <div style={{ maxWidth: 800, margin: '0 auto' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: '1.5rem' }}>
            <Link href="/" style={{ color: 'var(--color-signal)', textDecoration: 'none', fontSize: '0.875rem', fontWeight: 500 }}>← Back to KDP Niche Finder</Link>
          </div>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', fontWeight: 700, color: 'var(--color-ink)', marginBottom: '1rem' }}>
            Disclaimer
          </h1>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '1rem', fontSize: '0.8125rem', color: 'var(--color-ink-2)' }}>
            <span><strong>Last updated:</strong> 2026-08-17</span>
            <span><strong>Effective date:</strong> 2026-08-17</span>
          </div>
        </div>
      </section>

      {/* Content */}
      <section style={{ padding: '56px 48px 80px' }}>
        <div style={{ maxWidth: 800, margin: '0 auto' }}>

          <Section id="general" title="1. General Disclaimer">
            <P>
              The information and tools provided by KDP Niche Finder (the &quot;Service&quot;) are for <strong>general informational and educational purposes only</strong>. We make no representations or warranties about the accuracy, completeness, or suitability of any information provided.
            </P>
            <P>
              By using the Service, you expressly agree that any reliance on the information provided is <strong>strictly at your own risk</strong>.
            </P>
          </Section>

          <Section id="ai-content" title="2. AI-Generated Content Disclaimer">
            <H3>2.1 Nature of AI output</H3>
            <P>
              Our niche recommendations, scores, action plans, and book title suggestions are generated by <strong>third-party large language models</strong> (currently OpenAI&apos;s GPT models and Anthropic&apos;s Claude). These outputs are:
            </P>
            <Ul items={[
              '<strong>Machine-generated</strong> and may contain errors, hallucinations, or outdated information',
              '<strong>Not verified</strong> against Amazon\'s official data',
              '<strong>Not reviewed</strong> by human experts',
              '<strong>Subject to change</strong> without notice as we improve our prompts and models',
            ]} />

            <H3>2.2 No professional advice</H3>
            <P>AI-generated content does <strong>not</strong> constitute:</P>
            <Ul items={[
              'Financial advice or investment guidance',
              'Legal advice or legal opinion',
              'Tax advice',
              'Business consulting or coaching',
              'Career counseling',
              'Marketing guarantees',
            ]} />
            <P>
              You should consult qualified professionals before making significant business decisions based on our recommendations.
            </P>
          </Section>

          <Section id="earnings" title="3. No Earnings or Income Guarantee">
            <P>
              Any revenue estimates, sales projections, or income figures shown by the Service are:
            </P>
            <Ul items={[
              '<strong>Estimates based on historical BSR data</strong> and statistical modeling',
              '<strong>Not guarantees</strong> of future performance',
              <><strong>Subject to many variables</strong> outside our control (Amazon algorithm changes, market shifts, seasonality, your marketing effort, book quality, cover design, etc.)</>,
            ]} />
            <P>
              <strong>Your actual results may be significantly different — including zero revenue.</strong> We do not guarantee that you will earn any specific amount, or any amount at all, by following our recommendations.
            </P>
          </Section>

          <Section id="amazon" title="4. Amazon and KDP Disclaimer">
            <H3>4.1 Not affiliated</H3>
            <P>
              KDP Niche Finder is an <strong>independent third-party tool</strong>. We are <strong>not affiliated with, endorsed by, sponsored by, or in partnership with</strong>:
            </P>
            <Ul items={[
              'Amazon.com, Inc.',
              'Kindle Direct Publishing (KDP)',
              'Audible, Inc.',
              'Any Amazon subsidiary',
            ]} />

            <H3>4.2 Trademarks</H3>
            <P>
              &quot;Amazon&quot;, &quot;Kindle Direct Publishing&quot;, &quot;KDP&quot;, &quot;Kindle&quot;, &quot;Audible&quot;, and related marks are <strong>trademarks of Amazon.com, Inc.</strong> or its affiliates, used here for informational and identification purposes only.
            </P>

            <H3>4.3 Data source limitations</H3>
            <P>Best Sellers Rank (BSR) data and sales estimates are:</P>
            <Ul items={[
              'Sourced from <strong>publicly available Amazon pages</strong> via third-party proxy services',
              '<strong>Not obtained through Amazon\'s official APIs</strong> (Amazon Product Advertising API)',
              '<strong>Delayed by 24-72 hours</strong> in most cases',
              '<strong>Subject to interruption</strong> if Amazon changes its terms or blocks our data collection',
              '<strong>Not guaranteed to be accurate, current, or complete</strong>',
            ]} />
            <P>
              We do not have access to your Amazon Seller Central account, your sales data, or any private Amazon information.
            </P>

            <H3>4.4 Compliance with Amazon ToS</H3>
            <P>We do <strong>not</strong>:</P>
            <Ul items={[
              'Access login-protected Amazon pages',
              'Scrape customer reviews, seller private data, or restricted areas',
              'Circumvent CAPTCHAs or other security measures',
              'Represent that our data is provided by or endorsed by Amazon',
            ]} />
            <P>
              Your use of Amazon KDP is governed solely by Amazon&apos;s agreements and policies. We are not responsible for changes to Amazon&apos;s program, fees, policies, or terms.
            </P>
          </Section>

          <Section id="third-party" title="5. Third-Party Tools and Comparisons">
            <P>
              The Service may reference, compare, or link to third-party tools including:
            </P>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '0.75rem' }}>
              {['Publisher Rocket', 'Book Bolt / Book Bolt 2.0', 'BookBeam', 'Helium 10', 'KDPSpy', 'Pubscout', 'NicheCatch', 'KDP Builder', 'KDPEasy', 'Low Content Profits'].map(tool => (
                <span key={tool} style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 6, padding: '4px 10px', fontSize: '0.8125rem', color: 'var(--color-ink-2)' }}>{tool}</span>
              ))}
            </div>
            <Ul items={[
              'All such references are for <strong>informational and comparison purposes only</strong>',
              'We are <strong>not affiliated with</strong> any of these brands',
              'All trademarks are the property of their respective owners',
              'We do not represent that our features, data accuracy, or pricing match any third party',
              'Pricing and features of third-party tools change frequently; verify directly with the provider',
            ]} />
          </Section>

          <Section id="availability" title="6. Service Availability">
            <P>We do not guarantee:</P>
            <Ul items={[
              'Uninterrupted access to the Service',
              'That any feature will be error-free',
              'That defects will be corrected',
              'That the Service or its servers are free of viruses or harmful components',
            ]} />
            <P>
              We may modify, suspend, or discontinue the Service at any time without notice.
            </P>
          </Section>

          <Section id="liability" title="7. Limitation of Liability">
            <P>
              To the maximum extent permitted by law, we are not liable for any direct, indirect, incidental, consequential, or special damages arising from your use of the Service, including but not limited to:
            </P>
            <Ul items={[
              'Lost profits or revenue',
              'Lost business opportunities',
              'Loss of data',
              'Business interruption',
              'Costs of substitute services',
            ]} />
            <P>
              Some jurisdictions do not allow limitations on damages; in such cases, the above applies to the maximum extent permitted.
            </P>
          </Section>

          <Section id="no-endorsement" title="8. No Endorsement">
            <P>
              Reference to any third-party product, service, or company does not constitute or imply our endorsement, sponsorship, or recommendation. You should independently evaluate any third-party offerings.
            </P>
          </Section>

          <Section id="changes" title="9. Changes to This Disclaimer">
            <P>
              We may update this Disclaimer at any time. Continued use after changes constitutes acceptance.
            </P>
          </Section>

          <Section id="contact" title="10. Contact">
            <P>
              For questions about this Disclaimer, contact <strong>legal@kdpnichefinder.net</strong>.
            </P>
          </Section>

          {/* Source references */}
          <section style={{ marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid var(--color-border)' }}>
            <p style={{ fontSize: '0.8125rem', color: 'var(--color-ink-3)', fontStyle: 'italic' }}>
              This is a draft legal page for compliance review. Final wording must be approved by a licensed attorney before production deployment.
            </p>
          </section>

        </div>
      </section>

      <style>{`
        @media (max-width: 768px) {
          section[style*="padding: 56px"] { padding: 32px 16px 48px !important; }
          section[style*="padding: 64px 48px"] { padding: 40px 16px 32px !important; }
        }
        h2 { scroll-margin-top: 80px; }
        h3 { scroll-margin-top: 80px; }
      `}</style>
    </div>
  )
}
